### ISSUE TITLE
AADSTS70002 ERROR

### ISSUE THREAD

**Issue by danilocanel** [AzureAD/azure-activedirectory-library-for-java#139]
Hello everyone, I have the below error and I can't login:

Enter username: XXXXXX
Enter password: XXXXXX
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.\r\nTrace ID: 50d6b211-e780-4dd2-8265-8b9725ba1f00\r\nCorrelation ID: 2e0e8d95-8949-4caa-b735-6aec2d77f2fd\r\nTimestamp: 2017-04-09 21:14:43Z","error":"invalid_client"}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at PublicClient.getAccessTokenFromUserCredentials(PublicClient.java:49)
	at PublicClient.main(PublicClient.java:27)
Caused by: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.\r\nTrace ID: 50d6b211-e780-4dd2-8265-8b9725ba1f00\r\nCorrelation ID: 2e0e8d95-8949-4caa-b735-6aec2d77f2fd\r\nTimestamp: 2017-04-09 21:14:43Z","error":"invalid_client"}
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:108)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:876)
	at com.microsoft.aad.adal4j.AuthenticationContext.access$100(AuthenticationContext.java:64)
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:172)
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:161)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

BUILD FAILURE

Total time: 11.963s
Finished at: Sun Apr 09 15:14:43 CST 2017
Final Memory: 7M/245M

Thank you.

**Comment by danilocanel** [comment]
I re create the application in Azure how to a native application and grant the permissions for this.
