### ISSUE TITLE
Does it works?!

### ISSUE THREAD

**Issue by Slmba** [AzureAD/azure-activedirectory-library-for-java#143]
Hello. I'm trying to run adal4j auth and get NPE (lib exception). Reason - 
DEBUG com.microsoft.aad.adal4j.MexParser - No matching policies
What it's mean? And how make it works.

`
private final static String AUTHORIZATION_ENDPOINT_COMMON = "https://login.microsoftonline.com/common/";
private static AuthenticationResult getAccessTokenFromUserCredentials(
            String username, String password) throws Exception {
        AuthenticationContext context = null;
        AuthenticationResult result = null;
        ExecutorService service = null;
        try {
            service = Executors.newFixedThreadPool(1);
            context = new AuthenticationContext(AUTHORIZATION_ENDPOINT_COMMON, false, service);
            Future<AuthenticationResult> future = context.acquireToken(
                    "https://graph.windows.net", CLIENT_ID, username, password,
                    null);
            result = future.get();
        } finally {
            service.shutdown();
        }

        if (result == null) {
            throw new ServiceUnavailableException(
                    "authentication result was null");
        }
        return result;
    }`

Stacktrace:
23:21:40.958 [pool-1-thread-1] INFO com.microsoft.aad.adal4j.UserDiscoveryRequest - [Correlation ID: null] Sent (null) Correlation Id is not same as received (null).
23:21:41.845 [pool-1-thread-1] DEBUG com.microsoft.aad.adal4j.MexParser - No matching policies
23:21:41.848 [pool-1-thread-1] ERROR com.microsoft.aad.adal4j.AuthenticationContext - [Correlation ID: 7ebc2eb5-2a12-4465-9317-28719cad8be2] Request to acquire token failed.
java.lang.NullPointerException: null
	at com.microsoft.aad.adal4j.WSTrustRequest.execute(WSTrustRequest.java:61)
	at com.microsoft.aad.adal4j.AuthenticationContext.processPasswordGrant(AuthenticationContext.java:839)
	at com.microsoft.aad.adal4j.AuthenticationContext.access$000(AuthenticationContext.java:64)
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:171)
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:161)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Slmba** [comment]
pass contains specials, username contains @

**Comment by SomkaPe** [comment]
PasswordCredentialsGrant does not work with MSA accounts, it supposed to be used by with AAD and Federated accounts.
