### ISSUE TITLE
NoSuchMethodError from JWTClaimsSet. Java version issue?

### ISSUE THREAD

**Issue by kpratik16** [AzureAD/azure-activedirectory-library-for-java#178]
Hi,

I am using adal4j version 1.3.0 in Java 1.8 in Spark Streaming Application. It works fine on local machine but when testing it on cluster (again Java 1.8), it throws error as below. Am I missing something?

```
java.lang.NoSuchMethodError: com.nimbusds.jwt.JWTClaimsSet.<init>(Ljava/util/Map;Lcom/nimbusds/jwt/JWTClaimsSet;)V
	at com.nimbusds.jwt.JWTClaimsSet$Builder.build(JWTClaimsSet.java:306)
	at com.microsoft.aad.adal4j.JwtHelper.buildJwt(JwtHelper.java:67)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireToken(AuthenticationContext.java:384)
```

**Comment by Killinspoon** [comment]
Hi, did you happen to find a solution to this? I'm having the same issue.
