### ISSUE TITLE
Unable to connect fetch token for client cert auth for Azure key vault.

### ISSUE THREAD

**Issue by icetoad** [AzureAD/azure-activedirectory-library-for-java#254]
This error is being thrown in one of the projects that uses a module that does the client cert based auth to connect to Azure key vault. The other projects, however, are able to use this module to successfully talk to the Azure KV. Any pointers?
`
java.lang.VerifyError: Cannot inherit from final class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.microsoft.aad.adal4j.AuthenticationContext.acquireToken(AuthenticationContext.java:346)
`

**Comment by sangonzal** [comment]
@icetoad What version of ADAL4J are you using? From poking around the internet, it seems that this can be caused by having multiple versions of a dependency in your classpath. Can you check if this project or any of it's dependencies is bringing in a different version of ADAL4J?
