### ISSUE TITLE
Service-to-service access token request - AADSTS50058: A silent sign-in request was sent but no user is signed in.

### ISSUE THREAD

**Issue by ayrjegan** [AzureAD/azure-activedirectory-library-for-java#258]
Need to access the registered app's APIs from a Daemon/Faceless account. Followed the below link and able to get the response as per the example:
[]https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-client-creds-grant-flow 

However while using the bearer token to access the API, getting the below error:

```

com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS50058: A silent sign-in request was sent but no user is signed in.\r\nTrace ID: 61807035-678a-4456-8353-f353485e2800\r\nCorrelation ID: 9f16afb9-4d0c-4dd0-b0dd-9cdeaadfeed5\r\nTimestamp: 2019-03-21 13:08:43Z","error":"invalid_grant"}
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:128) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47) ~[adal4j-1.6.0.jar:1.6.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

[2m2019-03-21 18:38:43.429[0;39m [31mERROR[0;39m [35m12060[0;39m [2m---[0;39m [2m[nio-8080-exec-3][0;39m [36mc.m.a.s.a.aad.AADAuthenticationFilter   [0;39m [2m:[0;39m Failed to acquire graph api token.

java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS50058: A silent sign-in request was sent but no user is signed in.\r\nTrace ID: 61807035-678a-4456-8353-f353485e2800\r\nCorrelation ID: 9f16afb9-4d0c-4dd0-b0dd-9cdeaadfeed5\r\nTimestamp: 2019-03-21 13:08:43Z","error":"invalid_grant"}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_111]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_111]
	at com.microsoft.azure.spring.autoconfigure.aad.AzureADGraphClient.acquireTokenForGraphApi(AzureADGraphClient.java:148) ~[azure-spring-boot-2.1.2.jar:na]
	at com.microsoft.azure.spring.autoconfigure.aad.AADAuthenticationFilter.doFilterInternal(AADAuthenticationFilter.java:74) ~[azure-spring-boot-2.1.2.jar:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]

```
![client_credentials1](https://user-images.githubusercontent.com/6181506/54754825-7ce0c500-4c0a-11e9-8c2b-002119cb76a9.PNG)
![access_resource2](https://user-images.githubusercontent.com/6181506/54754836-82d6a600-4c0a-11e9-8f3a-b91717cfaeec.PNG)

**Comment by sangonzal** [comment]
@ayrjegan Is the client application registered in the Azure AD portal as a confidential/web application? Take a look at this (sample)[https://github.com/Azure-Samples/active-directory-dotnet-daemon], although it is for the ADAL.NET, it is for the same scenario and the application registration steps should be exactly the same.

**Comment by ayrjegan** [comment]
Hi, yes the application is registered and it's working fine with AAD user credentials, tested with Authorization Code flow. I am testing the same application for client credentials workflow.

**Comment by psignoret** [comment]
@ayrjegan The issue here is not that your client app is not able to use ADAL4J to obtain an access token, but instead, that the API you are calling is not accepting the access token. Your API is using [AADAuthenticationFilter] from the [Spring Boot Starter for Azure AD](https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-starters/azure-active-directory-spring-boot-starter), which does not currently support the client credentials flow (i.e. "app-only")--it expects all tokens it receives to also identify a user. 

This has already been raised as an issue over at Microsoft/azure-spring-boot#549, which I think is the more correct place to track this.

**Comment by ayrjegan** [comment]
> @ayrjegan The issue here is not that your client app is not able to use ADAL4J to obtain an access token, but instead, that the API you are calling is not accepting the access token. Your API is using [AADAuthenticationFilter] from the [Spring Boot Starter for Azure AD](https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-starters/azure-active-directory-spring-boot-starter), which does not currently support the client credentials flow (i.e. "app-only")--it expects all tokens it receives to also identify a user.
> 
> This has already been raised as an issue over at [Microsoft/azure-spring-boot#549](https://github.com/Microsoft/azure-spring-boot/issues/549), which I think is the more correct place to track this.

@psignoret Thanks for redirecting me to the existing issue & it helped solving my use case.
