### ISSUE TITLE
Not working with "Manage app passwords for two-step verification"

### ISSUE THREAD

**Issue by mores** [AzureAD/azure-activedirectory-library-for-java#273]
Our Admins have turned on app passwords following this guide: https://docs.microsoft.com/en-us/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords

When trying to use this username and password with adal4j, we are unable to login and receive the following stack trace:
`        at com.microsoft.aad.adal4j.HttpHelper.readResponseFromConnection(HttpHelper.java:84) ~[adal4j-1.6.4.jar:1.6.4]
        at com.microsoft.aad.adal4j.HttpHelper.getResponse(HttpHelper.java:181) ~[adal4j-1.6.4.jar:1.6.4]
        at com.microsoft.aad.adal4j.HttpHelper.executePostRequest(HttpHelper.java:170) ~[adal4j-1.6.4.jar:1.6.4]
        at com.microsoft.aad.adal4j.HttpHelper.executeHttpPost(HttpHelper.java:65) ~[adal4j-1.6.4.jar:1.6.4]
        at com.microsoft.aad.adal4j.WSTrustRequest.execute(WSTrustRequest.java:71) ~[adal4j-1.6.4.jar:1.6.4]
        at com.microsoft.aad.adal4j.WSTrustRequest.execute(WSTrustRequest.java:88) ~[adal4j-1.6.4.jar:1.6.4]
        at com.microsoft.aad.adal4j.AcquireTokenCallable.processPasswordGrant(AcquireTokenCallable.java:137) ~[adal4j-1.6.4.jar:1.6.4]
        at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:60) ~[adal4j-1.6.4.jar:1.6.4]
        at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38) ~[adal4j-1.6.4.jar:1.6.4]
        at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47) [adal4j-1.6.4.jar:1.6.4]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]`

**Comment by sangonzal** [comment]
@mores Username and password flow will not work with MFA or any other conditional access policy. MFA requires an interactive flow to be use (such as [authentication code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code) ), so the STS has the opportunity to present a dialog to the user to providing details about the MFA.  There is a [wiki page](https://github.com/AzureAD/azure-activedirectory-library-for-java/wiki/Acquire-tokens) on some of the other flows as well.
