### ISSUE TITLE
java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes

### ISSUE THREAD

**Issue by baidehig** [AzureAD/azure-activedirectory-library-for-java#303]
I am trying to get the Azure bearer token from my spring 5.1.x application, added the com.azure.adal4j-1.6.6 jar and oauth2-oidc-sdk-9.1 jar.

Took reference from - https://docs.microsoft.com/en-us/archive/blogs/azureossds/authenticating-azure-resource-management-rest-api-requests-using-java

On running my application, getting below error:
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at TestClass.getAccessTokenFromUserCredentials(TestClass.java:65)
	at TestClass.main(TestClass.java:32)
Caused by: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:158)
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:86)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:930)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.nimbusds.oauth2.sdk.http.CommonContentTypes
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more

Is it a known issue? This class file(com.nimbusds.oauth2.sdk.http.CommonContentTypes) is present as part of my application pom.

**Comment by sangonzal** [comment]
@baidehig ADAL is no longer receiving updates and will soon be deprecated. Please take a look at [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-java), which is the V2 library and supports all scenarios that ADAL supports. If you run into any issues using MSAL, please open an issue in that repository.
