### ISSUE TITLE
aadl4j throws an NPE when encountering a 404 on an invalid URL.

### ISSUE THREAD

**Issue by jmspring** [AzureAD/azure-activedirectory-library-for-java#48]
Using sample code below and the following URL, the stack trace included results.  Note the double slash in the URL.  NPEs should be caught.

URL -- https://login.microsoftonline.com//618c8322-bd3e-4c3a-b1de-be5fcee2efe8/oauth2/authorize

conn.getResponseCode() is 404.

Call to conn.getErrorStream doesn't check for null.

Stack trace (using most recent git repo):

java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.innerdot.azure.rest.example.ApplicationAuthExample.main(ApplicationAuthExample.java:79)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at com.microsoft.aad.adal4j.AdalOAuthRequest.processAndReadResponse(AdalOAuthRequest.java:143)
	at com.microsoft.aad.adal4j.AdalOAuthRequest.send(AdalOAuthRequest.java:73)
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:72)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:831)
	at com.microsoft.aad.adal4j.AuthenticationContext.access$100(AuthenticationContext.java:63)
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:130)
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:119)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jave code snippet:

	try {
            service = Executors.newFixedThreadPool(1);
		String url = AUTHORIZATION_ENDPOINT + "/" + tenantId + "/oauth2/authorize";
		System.out.println("url -- " + url);
            context = new AuthenticationContext(url, 
                                                false, 
                                                service);
            Future<AuthenticationResult> future = null;
            future = context.acquireToken(ARM_ENDPOINT, clientId,
                                          username, credential, null);
            result = future.get();
        } catch (Exception ex) {
            System.out.println("Exception: " + ex.toString());
            System.exit(1);
        } finally {
            service.shutdown();
        }

**Comment by kpanwar** [comment]
fixed in 1.1.0
