### ISSUE TITLE
AuthenticationContext fails if password contains special character ("")

### ISSUE THREAD

**Issue by amargehani** [AzureAD/azure-activedirectory-library-for-java#68]
AuthenticationContext.acquireToken(String resource, String clientId, String username, String password, AuthenticationCallback callback) fails always and gives **Server returned HTTP response code: 500 for URL: https://msft.sts.microsoft.com/adfs/services/trust/2005/usernamemixed** when the user contains (double quotes "") or (single quotes '') or # in the password.
I am using Adalj 1.1.1 version . With reference to issue # 28 , other special characters works.

**StackTrace:**

2015-10-22 16:04:15 [ERROR] AuthenticationContext - [Correlation ID: fe07e105-9371-48e0-a0eb-c274421b9e8a] Request to acquire token failed. (p: default-threadpool; w: Idle)
java.io.IOException: Server returned HTTP response code: 500 for URL: https://msft.sts.microsoft.com/adfs/services/trust/2005/usernamemixed
                at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627) ~[na:1.7.0_85]
                at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.7.0_85]
                at com.microsoft.aad.adal4j.HttpHelper.readResponseFromConnection(HttpHelper.java:86) ~[adal4j-1.1.1.jar:1.1.1]
                at com.microsoft.aad.adal4j.HttpHelper.getResponse(HttpHelper.java:182) ~[adal4j-1.1.1.jar:1.1.1]
                at com.microsoft.aad.adal4j.HttpHelper.executePostRequest(HttpHelper.java:172) ~[adal4j-1.1.1.jar:1.1.1]
                at com.microsoft.aad.adal4j.HttpHelper.executeHttpPost(HttpHelper.java:81) ~[adal4j-1.1.1.jar:1.1.1]
                at com.microsoft.aad.adal4j.WSTrustRequest.execute(WSTrustRequest.java:61) ~[adal4j-1.1.1.jar:1.1.1]
                at com.microsoft.aad.adal4j.AuthenticationContext.processPasswordGrant(AuthenticationContext.java:801) [adal4j-1.1.1.jar:1.1.1]
                at com.microsoft.aad.adal4j.AuthenticationContext.access$000(AuthenticationContext.java:64) [adal4j-1.1.1.jar:1.1.1]
                at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:140) [adal4j-1.1.1.jar:1.1.1]
                at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:130) [adal4j-1.1.1.jar:1.1.1]
                at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_85]

**Comment by SomkaPe** [comment]
We do escape user credentials, So special characters should not be an issue.
I suspect that the reason of mentioned exception was wrong password, anyway it is hard to say because we did not log error details.
I have added logging of non-200 http responses:
https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/121

**Comment by brentschmaltz** [comment]
@amargehani if this fix does not help you please reopen this issue.
