### ISSUE TITLE
ClassCastException when I build

### ISSUE THREAD

**Issue by AmaniSalah** [AzureAD/azure-activedirectory-library-for-java#88]
I'm getting this error when I build, any idea why?

2218 [pool-1-thread-1] ERROR com.microsoft.aad.adal4j.AuthenticationContext - [Correlation ID: ac256c7c-b9ae-41ff-b39c-f0746a2275f7] Request to acquire token failed.
java.lang.ClassCastException: sun.net.www.protocol.https.HttpsURLConnectionImpl cannot be cast to javax.net.ssl.HttpsURLConnection
    at com.microsoft.aad.adal4j.HttpHelper.openConnection(HttpHelper.java:102)
    at com.microsoft.aad.adal4j.HttpHelper.openConnection(HttpHelper.java:115)
    at com.microsoft.aad.adal4j.HttpHelper.executeHttpGet(HttpHelper.java:49)
    at com.microsoft.aad.adal4j.AuthenticationAuthority.doDynamicInstanceDiscovery(AuthenticationAuthority.java:146)
    at com.microsoft.aad.adal4j.AuthenticationAuthority.doInstanceDiscovery(AuthenticationAuthority.java:130)
    at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:813)
    at com.microsoft.aad.adal4j.AuthenticationContext.access$1(AuthenticationContext.java:806)
    at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:175)
    at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Warning: Could not get charToByteConverterClass!
638 [main] INFO com.microsoft.aad.adal4j.WSTrustResponse - Found token of type: urn:oasis:names:tc:SAML:1.0:assertion

**Comment by kpanwar** [comment]
what is your Sun JDK version?
