### ISSUE TITLE
java.lang.NoClassDefFoundError: com/nimbusds/jwt/JWT

### ISSUE THREAD

**Issue by armharish** [AzureAD/azure-activedirectory-library-for-java#91]
Hi,

I am getting below error while trying to execute source. I am just trying to get auth toekn and refresh token.

user id : <myuser id> Password: <my password> Exception in thread "main" java.lang.NoClassDefFoundError: com/nimbusds/jwt/JWT
	at com.cts.azure.AzureAuthToekn.getAccessTokenFromUserCredentials(AzureAuthToekn.java:48)
	at com.cts.azure.AzureAuthToekn.main(AzureAuthToekn.java:33)
Caused by: java.lang.ClassNotFoundException: com.nimbusds.jwt.JWT
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

**Comment by kpanwar** [comment]
I don't see ADAL being referred anywhere here. Have you referenced ADAL correctly in you pom.xml? If so then maven should pull all the dependencies.

**Comment by armharish** [comment]
You are right - It resolved after fixing POM. Thank you.
