### ISSUE TITLE
not supported for this API version

### ISSUE THREAD

**Issue by patrickjamesbarry** [AzureAD/azure-activedirectory-library-for-java#96]
We are getting this error when trying to authenticate with a valid user.

Exception in thread "main" java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS70001: Application 'a2333e4-1eaf-4b66-rr04-ed825e0dxxx' is not supported for this API version.\r\nTrace ID: e37d4bda-3db7-4dd1-b690-5d127b1a5ss5\r\nCorrelation ID: 4de96623-6669-4a17-bd44-3c1ecc722ff1\r\nTimestamp: 2016-06-28 20:10:17Z","error":"unauthorized_client"}
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)

**Comment by tossb** [comment]
@patrickjamesbarry 
I encountered this as well using a B2C tenant.  I believe the issue has to do with the getRedirectUrl method in basic filter not have the v2.0 in the URI.  Hope that helps.  I get another error down the path while attempting to get the access token.
